#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "✨ Commit-msg hook started...🚀"
echo "✨ Verifying the commit message...📝"
start=$(date +%s)
npx --no -- commitlint --edit
end=$(date +%s)
echo "✨ Done in $(($end-$start))s"
echo
