#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ✨ Post-merge hook started...🚀
echo ✨ Merge in progress...⏰
echo ✨ Installing packages...📦
start=$(date +%s)
npx bun install
end=$(date +%s)
echo "✨ Done in $(($end-$start))s."
